import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import StartApp from '@/components/StartApp'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>
        {children}
      </body>

    </html>
  )
}
